version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    depends_on:
      web:
        condition: service_healthy
    environment:
      - APP_URL=http://web:3000
    volumes:
      - ./test-results:/app/test-results
    profiles:
      - testing